import './globals.css';
import Navbar from '../components/Navbar/index';
import Footer from '../components/Footer/index';

export const metadata = {
  title: 'web3Template',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
